'use client';

import { ProfileResult } from '@/lib/types/results';
import { categoryDefinitions } from '@/lib/quiz/categories';

type Locale = 'en' | 'tr';

/**
 * Generate and download a PDF report of the profile results.
 * Uses dynamic imports for html2canvas and jsPDF to avoid SSR issues.
 */
export async function generatePDF(
  profile: ProfileResult,
  locale: Locale = 'en'
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');

  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper to add text with wrapping
  const addText = (text: string, fontSize: number, isBold = false, color = '#1c4f48') => {
    doc.setFontSize(fontSize);
    doc.setTextColor(color);
    if (isBold) doc.setFont('helvetica', 'bold');
    else doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.4) + 4;
  };

  const addNewPage = () => {
    doc.addPage();
    y = margin;
  };

  // Cover page
  y = 60;
  addText('Hayırlısı', 28, true, '#2d9a89');
  y += 5;
  addText(
    locale === 'en'
      ? 'Marriage Compatibility Profile'
      : 'Evlilik Uyumu Profili',
    18,
    false,
    '#5a5046'
  );
  y += 10;
  addText(
    locale === 'en'
      ? `Generated: ${new Date(profile.completedAt).toLocaleDateString('en-US')}`
      : `Oluşturulma: ${new Date(profile.completedAt).toLocaleDateString('tr-TR')}`,
    11,
    false,
    '#857563'
  );

  // Profile type
  y += 20;
  addText(
    locale === 'en' ? 'Your Profile Type' : 'Profil Tipiniz',
    14,
    true,
    '#2d9a89'
  );
  addText(
    locale === 'en' ? profile.typeDescription.en : profile.typeDescription.tr,
    11,
    false,
    '#5a5046'
  );

  // Honesty calibration
  y += 10;
  addText(
    locale === 'en' ? 'Honesty Calibration' : 'Dürüstlük Kalibrasyonu',
    14,
    true,
    '#2d9a89'
  );
  addText(
    `${locale === 'en' ? 'Score' : 'Puan'}: ${profile.honestyCalibration.score}/100`,
    11,
    false,
    '#5a5046'
  );
  addText(
    `${locale === 'en' ? 'Consistency' : 'Tutarlılık'}: ${profile.overallConsistency}/100`,
    11,
    false,
    '#5a5046'
  );

  // Dimension details
  addNewPage();
  addText(
    locale === 'en' ? 'Dimension Breakdown' : 'Boyut Detayları',
    18,
    true,
    '#2d9a89'
  );
  y += 5;

  for (const dim of profile.dimensions) {
    if (y > 250) addNewPage();

    const catDef = categoryDefinitions[dim.categoryId];
    const name = locale === 'en' ? catDef?.nameEn : catDef?.nameTr;

    addText(name || dim.categoryId, 13, true, catDef?.color || '#2d9a89');

    const labels = locale === 'en'
      ? ['Position', 'Importance', 'Flexibility', 'Consistency']
      : ['Pozisyon', 'Önem', 'Esneklik', 'Tutarlılık'];

    addText(
      `${labels[0]}: ${dim.selfScore}  |  ${labels[1]}: ${dim.importanceScore}  |  ${labels[2]}: ${dim.flexibilityScore}  |  ${labels[3]}: ${dim.consistencyScore}`,
      10,
      false,
      '#5a5046'
    );

    if (dim.dealBreaker) {
      addText(
        locale === 'en' ? '⚠ Deal-Breaker' : '⚠ Kırmızı Çizgi',
        10,
        true,
        '#dc4020'
      );
    }
    y += 4;
  }

  // Footer
  addNewPage();
  y = 250;
  addText(
    locale === 'en'
      ? 'Generated by Hayırlısı — Open Source Marriage Compatibility Tool'
      : 'Hayırlısı tarafından oluşturuldu — Açık Kaynak Evlilik Uyumu Aracı',
    9,
    false,
    '#b0a08a'
  );

  doc.save(`hayirlisi-profile-${profile.id}.pdf`);
}
