import { Category, CategoryId, CategoryWeight } from '@/lib/types/quiz';

export const categoryDefinitions: Record<CategoryId, Omit<Category, 'questions'>> = {
  values: {
    id: 'values',
    nameEn: 'Core Values & Worldview',
    nameTr: 'Temel Değerler ve Dünya Görüşü',
    descriptionEn: 'Your religious beliefs, moral framework, life philosophy, and social values form the foundation of who you are. Research shows that value congruence is the strongest assortative mating signal — couples who share core values have fundamentally stronger foundations.',
    descriptionTr: 'Dini inançlarınız, ahlaki çerçeveniz, yaşam felsefeniz ve sosyal değerleriniz kim olduğunuzun temelini oluşturur. Araştırmalar, değer uyumunun en güçlü eş seçimi sinyali olduğunu gösteriyor — temel değerleri paylaşan çiftlerin temelleri çok daha sağlam oluyor.',
    iconName: 'Compass',
    weight: 'CRITICAL',
    color: '#2d9a89',
    researchCitationEn: 'Luo & Klohnen (2005): Value congruence is the strongest assortative mating signal. Lehrer & Chiswick (1993): Same-faith couples have 13% 5-year divorce rate vs. 40% for interfaith couples.',
    researchCitationTr: 'Luo & Klohnen (2005): Değer uyumu en güçlü eş seçimi sinyalidir. Lehrer & Chiswick (1993): Aynı inançtan çiftlerde 5 yıllık boşanma oranı %13 iken, farklı inançlardan çiftlerde %40\'tır.',
  },
  communication: {
    id: 'communication',
    nameEn: 'Communication & Conflict',
    nameTr: 'İletişim ve Çatışma',
    descriptionEn: 'How you handle disagreements is the single strongest predictor of relationship survival. Contempt — not conflict itself — destroys marriages. Your repair attempt readiness and conflict resolution patterns matter more than how often you argue.',
    descriptionTr: 'Anlaşmazlıkları nasıl ele aldığınız, ilişki sürdürülebilirliğinin en güçlü göstergesidir. Evlilikleri yıkan çatışmanın kendisi değil, küçümsemedir. Onarım girişimleriniz ve çatışma çözme biçimleriniz, ne sıklıkta tartıştığınızdan çok daha önemlidir.',
    iconName: 'MessageCircle',
    weight: 'CRITICAL',
    color: '#3b82f6',
    researchCitationEn: 'Gottman & Levenson: The "Four Horsemen" (criticism, contempt, defensiveness, stonewalling) predict divorce with 93.6% accuracy. Contempt alone is the strongest single predictor.',
    researchCitationTr: 'Gottman & Levenson: "Dört Atlı" (eleştiri, küçümseme, savunmacılık, duvar örme) %93,6 doğrulukla boşanmayı öngörüyor. Küçümseme tek başına en güçlü gösterge.',
  },
  financial: {
    id: 'financial',
    nameEn: 'Financial Behavior',
    nameTr: 'Finansal Davranış',
    descriptionEn: 'Financial disagreements predict divorce more powerfully than disagreements about sex, household tasks, or in-laws. It\'s not about how much money you have — it\'s about how you relate to money.',
    descriptionTr: 'Finansal anlaşmazlıklar, cinsellik, ev işleri veya kayınvalide-kayınpeder konularındaki anlaşmazlıklardan çok daha güçlü bir şekilde boşanmayı öngörüyor. Mesele ne kadar paranız olduğu değil, parayla ilişkinizdir.',
    iconName: 'Wallet',
    weight: 'HIGH',
    color: '#eab308',
    researchCitationEn: 'Dew, Britt & Huston (2012): 25-year longitudinal study. Women who argue "often" about money are nearly 3x more likely to divorce. Financial conflicts last longer, are more heated, and less likely to be resolved.',
    researchCitationTr: 'Dew, Britt & Huston (2012): 25 yıllık uzun vadeli çalışma. Para konusunda "sık sık" tartışan kadınların boşanma olasılığı yaklaşık 3 kat daha fazla.',
  },
  family: {
    id: 'family',
    nameEn: 'Family & Children',
    nameTr: 'Aile ve Çocuklar',
    descriptionEn: 'Whether to have children is one of the few true binary incompatibilities — there is no compromise position. Beyond that, your parenting philosophy, extended family boundaries, and family-of-origin patterns profoundly shape your marriage.',
    descriptionTr: 'Çocuk sahibi olup olmamak, gerçek anlamda ikili uyumsuzluklardan biridir — uzlaşma noktası yoktur. Bunun ötesinde, ebeveynlik felsefeniz, geniş aile sınırlarınız ve yetiştirilme tarzınız evliliğinizi derinden şekillendirir.',
    iconName: 'Users',
    weight: 'HIGH',
    color: '#f97316',
    researchCitationEn: 'Research identifies wanting vs. not wanting children as one of the few true non-negotiable incompatibilities. Carroll & Doherty (2003): Pre-marital education reduces divorce risk by 30%.',
    researchCitationTr: 'Araştırmalar, çocuk isteme/istememe konusunu gerçek uzlaşılamaz uyumsuzluklardan biri olarak tanımlıyor. Carroll & Doherty (2003): Evlilik öncesi eğitim boşanma riskini %30 azaltıyor.',
  },
  goals: {
    id: 'goals',
    nameEn: 'Life Goals & Ambition',
    nameTr: 'Yaşam Hedefleri ve Hırs',
    descriptionEn: 'Where you want to go in life — geographically, professionally, and philosophically — shapes the practical reality of your partnership. Misaligned ambition levels create silent resentment over years.',
    descriptionTr: 'Hayatta nereye gitmek istediğiniz — coğrafi, mesleki ve felsefi olarak — ortaklığınızın pratik gerçekliğini şekillendirir. Uyumsuz hırs seviyeleri yıllar içinde sessiz bir kırgınlık yaratır.',
    iconName: 'Target',
    weight: 'HIGH',
    color: '#8b5cf6',
    researchCitationEn: 'Huston et al. (2001): The PAIR Project (13-year study) found that disillusionment — the decline of love and affection, not increasing hostility — is what distinguishes failed marriages.',
    researchCitationTr: 'Huston ve ark. (2001): PAIR Projesi (13 yıllık çalışma) başarısız evlilikleri ayırt edenin artan düşmanlık değil, hayal kırıklığı — sevgi ve şefkatin azalması — olduğunu bulmuştur.',
  },
  intimacy: {
    id: 'intimacy',
    nameEn: 'Intimacy & Affection',
    nameTr: 'Yakınlık ve Şefkat',
    descriptionEn: 'Physical and emotional intimacy needs vary enormously between people. Research shows a strong correlation (r = .37–.49) between sexual satisfaction and marital satisfaction. Understanding your own needs is the first step.',
    descriptionTr: 'Fiziksel ve duygusal yakınlık ihtiyaçları kişiden kişiye büyük farklılık gösterir. Araştırmalar cinsel tatmin ile evlilik tatmini arasında güçlü bir korelasyon (r = ,37–,49) olduğunu gösteriyor.',
    iconName: 'Heart',
    weight: 'HIGH',
    color: '#ec4899',
    researchCitationEn: 'Meta-analytic correlation between sexual satisfaction and marital satisfaction: r = .37–.49. Must-match on frequency and intensity; specific preferences are negotiable.',
    researchCitationTr: 'Cinsel tatmin ile evlilik tatmini arasındaki meta-analitik korelasyon: r = ,37–,49. Sıklık ve yoğunluk konusunda uyum şart; spesifik tercihler müzakere edilebilir.',
  },
  household: {
    id: 'household',
    nameEn: 'Household & Daily Life',
    nameTr: 'Ev Hayatı ve Günlük Yaşam',
    descriptionEn: 'The daily reality of shared living matters more than people expect. Research shows that perceived fairness in household labor matters more than the actual division — but the perception gap can become a major source of conflict.',
    descriptionTr: 'Birlikte yaşamanın günlük gerçekliği insanların beklediğinden daha önemlidir. Araştırmalar, ev işlerinde algılanan adaletin gerçek bölüşümden daha önemli olduğunu gösteriyor.',
    iconName: 'Home',
    weight: 'MEDIUM',
    color: '#14b8a6',
    researchCitationEn: 'Hochschild (1989); Frisco & Williams (2003): Perceived fairness > actual division. Both complementary and egalitarian models work when perceived as fair.',
    researchCitationTr: 'Hochschild (1989); Frisco & Williams (2003): Algılanan adalet > gerçek bölüşüm. Hem tamamlayıcı hem eşitlikçi modeller adil algılandığında işler.',
  },
  health: {
    id: 'health',
    nameEn: 'Health & Lifestyle',
    nameTr: 'Sağlık ve Yaşam Tarzı',
    descriptionEn: 'Substance use discrepancies predict significant satisfaction decline over time. Beyond substances, your approach to diet, exercise, and mental health creates the daily environment of your partnership.',
    descriptionTr: 'Madde kullanım farklılıkları zamanla belirgin tatminsizlik düşüşü öngörüyor. Madde kullanımının ötesinde, diyet, egzersiz ve ruh sağlığına yaklaşımınız ortaklığınızın günlük ortamını oluşturur.',
    iconName: 'Activity',
    weight: 'MEDIUM',
    color: '#22c55e',
    researchCitationEn: 'Homish & Leonard (2007): Substance use discrepancies predict significant satisfaction decline over 7 years. Concordance matters — both using or both abstaining > discordant.',
    researchCitationTr: 'Homish & Leonard (2007): Madde kullanım farklılıkları 7 yıl boyunca önemli tatmin düşüşü öngörüyor. Uyum önemli — her ikisinin de kullanması veya kullanmaması > uyumsuzluk.',
  },
  social: {
    id: 'social',
    nameEn: 'Social Life & Boundaries',
    nameTr: 'Sosyal Hayat ve Sınırlar',
    descriptionEn: 'How much social interaction you need, your relationship with in-laws, and your friendship boundaries shape the daily texture of married life. Individual agreeableness matters more than similarity here.',
    descriptionTr: 'Ne kadar sosyal etkileşime ihtiyaç duyduğunuz, kayınvalide-kayınpeder ilişkiniz ve arkadaşlık sınırlarınız evli hayatın günlük dokusunu şekillendirir.',
    iconName: 'Users2',
    weight: 'MEDIUM',
    color: '#06b6d4',
    researchCitationEn: 'Dyrenforth et al. (2010): Individual agreeableness matters more than personality similarity for relationship satisfaction.',
    researchCitationTr: 'Dyrenforth ve ark. (2010): İlişki tatmini için kişilik benzerliğinden çok bireysel uyumluluk önemlidir.',
  },
  growth: {
    id: 'growth',
    nameEn: 'Personal Growth',
    nameTr: 'Kişisel Gelişim',
    descriptionEn: '"Growth beliefs" — the belief that relationships require work and can improve — predict better outcomes than "destiny beliefs" that compatibility is fixed. Your openness to change shapes your marriage\'s trajectory.',
    descriptionTr: '"Büyüme inançları" — ilişkilerin çalışma gerektirdiği ve gelişebileceği inancı — uyumluluğun sabit olduğuna dair "kader inançları"ndan daha iyi sonuçlar öngörüyor.',
    iconName: 'Sprout',
    weight: 'MEDIUM',
    color: '#a855f7',
    researchCitationEn: 'Growth beliefs vs. destiny beliefs research: Partners who believe relationships can improve through effort show better conflict resolution and higher long-term satisfaction.',
    researchCitationTr: 'Büyüme inançları vs. kader inançları araştırması: İlişkilerin çabayla gelişebileceğine inanan eşler daha iyi çatışma çözümü ve daha yüksek uzun vadeli tatmin gösteriyor.',
  },
  worklife: {
    id: 'worklife',
    nameEn: 'Work-Life Balance',
    nameTr: 'İş-Yaşam Dengesi',
    descriptionEn: 'Work-family conflict negatively predicts relationship quality. Your expectations about work hours, career priority, and availability create the practical framework of daily married life.',
    descriptionTr: 'İş-aile çatışması ilişki kalitesini olumsuz yönde etkiler. Çalışma saatleri, kariyer önceliği ve müsaitlik konusundaki beklentileriniz günlük evli hayatın pratik çerçevesini oluşturur.',
    iconName: 'Briefcase',
    weight: 'MEDIUM',
    color: '#6366f1',
    researchCitationEn: 'Work-family conflict meta-analysis: r = –.19 with relationship quality. Both complementary and dual-career models are workable if expectations align.',
    researchCitationTr: 'İş-aile çatışması meta-analizi: ilişki kalitesiyle r = –,19 korelasyon. Beklentiler uyumluysa hem tamamlayıcı hem çift kariyer modelleri işler.',
  },
  aesthetic: {
    id: 'aesthetic',
    nameEn: 'Aesthetic & Lifestyle Preferences',
    nameTr: 'Estetik ve Yaşam Tarzı Tercihleri',
    descriptionEn: 'While these preferences have the weakest direct link to marital satisfaction, they often serve as proxies for deeper values about respect, control, and cultural identity. Pay attention to what your preferences reveal about your deeper needs.',
    descriptionTr: 'Bu tercihler evlilik tatminiyle en zayıf doğrudan bağlantıya sahip olsa da, genellikle saygı, kontrol ve kültürel kimlik hakkındaki daha derin değerlerin göstergesi olarak işlev görür.',
    iconName: 'Palette',
    weight: 'LOW',
    color: '#f43f5e',
    researchCitationEn: 'Research gap acknowledged. Clinically, aesthetic disagreements are often symptoms of deeper respect/control issues rather than standalone predictors.',
    researchCitationTr: 'Araştırma boşluğu kabul edilmektedir. Klinik olarak, estetik anlaşmazlıklar genellikle bağımsız göstergeler olmaktan çok, daha derin saygı/kontrol sorunlarının belirtileridir.',
  },
};

export const categoryOrder: CategoryId[] = [
  'values', 'communication', 'financial', 'family', 'goals', 'intimacy',
  'household', 'health', 'social', 'growth', 'worklife', 'aesthetic',
];

export const weightMultiplier: Record<CategoryWeight, number> = {
  CRITICAL: 3.0,
  HIGH: 2.0,
  MEDIUM: 1.0,
  LOW: 0.5,
};

export function getCategoryById(id: CategoryId) {
  return categoryDefinitions[id];
}

export function getCategoriesByWeight(weight: CategoryWeight) {
  return categoryOrder
    .map(id => categoryDefinitions[id])
    .filter(cat => cat.weight === weight);
}
