import { Question, CategoryId } from '@/lib/types/quiz';

// ─── VALUES ──────────────────────────────────────────────────────────
const valuesQuestions: Question[] = [
  {
    id: 'val-1',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How important is it that your partner shares your religious or spiritual beliefs?',
    textTr: 'Partnerinizin dini veya manevi inançlarınızı paylaşması ne kadar önemli?',
    likertLabels: { lowEn: 'Not important at all', lowTr: 'Hiç önemli değil', highEn: 'Absolutely essential', highTr: 'Kesinlikle vazgeçilmez' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'val-2',
    categoryId: 'values',
    type: 'scenario',
    textEn: 'Your partner donates a significant portion of income to charity without consulting you. How do you react?',
    textTr: 'Partneriniz sizinle görüşmeden gelirinizin önemli bir bölümünü bağışlıyor. Nasıl tepki verirsiniz?',
    options: [
      { id: 'val-2a', textEn: 'I\'d be upset — big financial decisions should be joint', textTr: 'Üzülürüm — büyük mali kararlar birlikte alınmalı', value: 1 },
      { id: 'val-2b', textEn: 'I\'d want to discuss it but understand the impulse', textTr: 'Konuşmak isterdim ama bu isteği anlıyorum', value: 2 },
      { id: 'val-2c', textEn: 'I\'d admire their generosity and support it', textTr: 'Cömertliğine hayran kalır ve desteklerdim', value: 3 },
      { id: 'val-2d', textEn: 'I\'d be thrilled — generosity is a core value for me', textTr: 'Çok sevinirdim — cömertlik benim için temel bir değer', value: 4 },
    ],
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'val-3',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How closely should your political views align with your partner\'s?',
    textTr: 'Siyasi görüşleriniz partnerinizinkiyle ne kadar örtüşmeli?',
    likertLabels: { lowEn: 'Can be very different', lowTr: 'Çok farklı olabilir', highEn: 'Must be nearly identical', highTr: 'Neredeyse aynı olmalı' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'val-4',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How important is honesty, even when the truth is uncomfortable?',
    textTr: 'Gerçek rahatsız edici olsa bile dürüstlük ne kadar önemli?',
    likertLabels: { lowEn: 'White lies are fine', lowTr: 'Küçük yalanlar olabilir', highEn: 'Total honesty always', highTr: 'Her zaman tam dürüstlük' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
    honestyPairId: 'val-4-pair',
  },
  {
    id: 'val-5',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How important is it that your partner shares your cultural traditions and heritage?',
    textTr: 'Partnerinizin kültürel geleneklerinizi ve mirasınızı paylaşması ne kadar önemli?',
    likertLabels: { lowEn: 'Not important', lowTr: 'Önemli değil', highEn: 'Very important', highTr: 'Çok önemli' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
];

// ─── COMMUNICATION ───────────────────────────────────────────────────
const communicationQuestions: Question[] = [
  {
    id: 'com-1',
    categoryId: 'communication',
    type: 'scenario',
    textEn: 'After a heated argument, what do you need most?',
    textTr: 'Sert bir tartışmanın ardından en çok neye ihtiyaç duyarsınız?',
    options: [
      { id: 'com-1a', textEn: 'Space to cool down before talking again', textTr: 'Tekrar konuşmadan önce sakinleşmek için alan', value: 1 },
      { id: 'com-1b', textEn: 'A short break, then resolve it the same day', textTr: 'Kısa bir mola, sonra aynı gün çözmek', value: 2 },
      { id: 'com-1c', textEn: 'To talk it through immediately until it\'s resolved', textTr: 'Çözülene kadar hemen konuşmak', value: 3 },
      { id: 'com-1d', textEn: 'Physical reassurance first, then discussion', textTr: 'Önce fiziksel yakınlık, sonra konuşma', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-2',
    categoryId: 'communication',
    type: 'likert',
    textEn: 'When your partner is upset, do you try to fix the problem or just listen?',
    textTr: 'Partneriniz üzgünken sorunu çözmeye mi çalışırsınız yoksa sadece dinler misiniz?',
    likertLabels: { lowEn: 'Always fix', lowTr: 'Her zaman çözerim', highEn: 'Always listen', highTr: 'Her zaman dinlerim' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-3',
    categoryId: 'communication',
    type: 'likert',
    textEn: 'How comfortable are you expressing vulnerability and deep emotions to your partner?',
    textTr: 'Partnerinize karşı savunmasızlığınızı ve derin duygularınızı ifade etmek ne kadar rahat geliyor?',
    likertLabels: { lowEn: 'Very uncomfortable', lowTr: 'Çok rahatsız edici', highEn: 'Completely comfortable', highTr: 'Tamamen rahat' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-4',
    categoryId: 'communication',
    type: 'scenario',
    textEn: 'Your partner raises their voice during an argument. What is your response?',
    textTr: 'Partneriniz tartışma sırasında sesini yükseltiyor. Nasıl tepki verirsiniz?',
    options: [
      { id: 'com-4a', textEn: 'I shut down and go silent', textTr: 'Kapanır ve sessizleşirim', value: 1 },
      { id: 'com-4b', textEn: 'I raise my voice too — it\'s how I express passion', textTr: 'Ben de sesimi yükseltirim — duygularımı böyle ifade ederim', value: 2 },
      { id: 'com-4c', textEn: 'I calmly ask them to lower their voice', textTr: 'Sakin bir şekilde sesini kısmasını isterim', value: 3 },
      { id: 'com-4d', textEn: 'I leave the room and come back later', textTr: 'Odadan çıkar ve sonra dönerim', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-5',
    categoryId: 'communication',
    type: 'likert',
    textEn: 'How important is it to say "I\'m sorry" after a conflict, even if you don\'t feel entirely wrong?',
    textTr: 'Tamamen hatalı hissetmeseniz bile bir çatışmanın ardından "Özür dilerim" demek ne kadar önemli?',
    likertLabels: { lowEn: 'Only if truly wrong', lowTr: 'Yalnızca gerçekten hatalıysam', highEn: 'Always — repair matters most', highTr: 'Her zaman — ilişkiyi onarmak önce gelir' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
    honestyPairId: 'com-5-pair',
  },
];

// ─── FINANCIAL ───────────────────────────────────────────────────────
const financialQuestions: Question[] = [
  {
    id: 'fin-1',
    categoryId: 'financial',
    type: 'scenario',
    textEn: 'How should married couples manage their money?',
    textTr: 'Evli çiftler paralarını nasıl yönetmeli?',
    options: [
      { id: 'fin-1a', textEn: 'Everything in one joint account', textTr: 'Her şey tek ortak hesapta', value: 1 },
      { id: 'fin-1b', textEn: 'Joint account for shared expenses, separate personal accounts', textTr: 'Ortak giderler için ortak hesap, ayrı kişisel hesaplar', value: 2 },
      { id: 'fin-1c', textEn: 'Mostly separate with agreed contributions to shared costs', textTr: 'Çoğunlukla ayrı, ortak giderlere kararlaştırılmış katkı', value: 3 },
      { id: 'fin-1d', textEn: 'Completely separate finances', textTr: 'Tamamen ayrı finanslar', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'fin-2',
    categoryId: 'financial',
    type: 'likert',
    textEn: 'How comfortable are you with taking on debt (mortgage, car loan, credit cards)?',
    textTr: 'Borç almaya (mortgage, araç kredisi, kredi kartı) ne kadar rahat bakıyorsunuz?',
    likertLabels: { lowEn: 'Avoid all debt', lowTr: 'Her türlü borçtan kaçınırım', highEn: 'Debt is a normal tool', highTr: 'Borç normal bir araçtır' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fin-3',
    categoryId: 'financial',
    type: 'likert',
    textEn: 'How much should you save versus enjoy life now?',
    textTr: 'Ne kadar biriktirmeli, ne kadar şimdinin tadını çıkarmalısınız?',
    likertLabels: { lowEn: 'Save aggressively', lowTr: 'Agresif biçimde biriktir', highEn: 'Enjoy the present', highTr: 'Şimdinin tadını çıkar' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fin-4',
    categoryId: 'financial',
    type: 'likert',
    textEn: 'At what spending amount should your partner consult you before purchasing?',
    textTr: 'Partneriniz hangi harcama tutarından itibaren satın almadan önce sizinle görüşmeli?',
    likertLabels: { lowEn: 'Any amount', lowTr: 'Her tutarda', highEn: 'Only very large purchases', highTr: 'Yalnızca çok büyük alımlarda' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fin-5',
    categoryId: 'financial',
    type: 'scenario',
    textEn: 'Your partner\'s family member asks for a large financial loan. What do you do?',
    textTr: 'Partnerinizin bir aile üyesi büyük bir mali borç istiyor. Ne yaparsınız?',
    options: [
      { id: 'fin-5a', textEn: 'Family comes first — we should help no matter what', textTr: 'Aile her şeyden önce gelir — ne olursa olsun yardım etmeliyiz', value: 1 },
      { id: 'fin-5b', textEn: 'Help if we can afford it, but set clear boundaries', textTr: 'Karşılayabiliyorsak yardım ederiz ama net sınırlar koyarız', value: 2 },
      { id: 'fin-5c', textEn: 'Only if they have a repayment plan', textTr: 'Yalnızca geri ödeme planları varsa', value: 3 },
      { id: 'fin-5d', textEn: 'Our household finances come first — politely decline', textTr: 'Hanemizdeki mali durum önce gelir — kibarca reddederiz', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── FAMILY ──────────────────────────────────────────────────────────
const familyQuestions: Question[] = [
  {
    id: 'fam-1',
    categoryId: 'family',
    type: 'dealbreaker',
    textEn: 'How important is having children to you?',
    textTr: 'Çocuk sahibi olmak sizin için ne kadar önemli?',
    likertLabels: { lowEn: 'Do not want children', lowTr: 'Çocuk istemiyorum', highEn: 'Children are essential', highTr: 'Çocuklar vazgeçilmez' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'fam-2',
    categoryId: 'family',
    type: 'scenario',
    textEn: 'How involved should extended family (in-laws) be in your married life?',
    textTr: 'Geniş aile (kayınpeder/kayınvalide) evlilik hayatınızda ne kadar yer almalı?',
    options: [
      { id: 'fam-2a', textEn: 'Very involved — family is everything', textTr: 'Çok dahil — aile her şeydir', value: 1 },
      { id: 'fam-2b', textEn: 'Regularly involved but with clear boundaries', textTr: 'Düzenli dahil ama net sınırlarla', value: 2 },
      { id: 'fam-2c', textEn: 'Occasional visits and holidays only', textTr: 'Yalnızca ara sıra ziyaretler ve tatiller', value: 3 },
      { id: 'fam-2d', textEn: 'Minimal involvement — our household is independent', textTr: 'Minimum dahliyet — hanemiz bağımsız', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'fam-3',
    categoryId: 'family',
    type: 'likert',
    textEn: 'How strictly should children be raised?',
    textTr: 'Çocuklar ne kadar katı bir şekilde yetiştirilmeli?',
    likertLabels: { lowEn: 'Very permissive', lowTr: 'Çok serbest', highEn: 'Very structured/strict', highTr: 'Çok düzenli/katı' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fam-4',
    categoryId: 'family',
    type: 'likert',
    textEn: 'Should one parent stay home with young children, or should both parents work?',
    textTr: 'Küçük çocuklarla bir ebeveyn evde mi kalmalı, yoksa her ikisi de çalışmalı mı?',
    likertLabels: { lowEn: 'One parent should stay home', lowTr: 'Bir ebeveyn evde kalmalı', highEn: 'Both should work', highTr: 'Her ikisi de çalışmalı' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fam-5',
    categoryId: 'family',
    type: 'scenario',
    textEn: 'Your aging parent needs daily care. What is the right approach?',
    textTr: 'Yaşlanan ebeveynin günlük bakıma ihtiyacı var. Doğru yaklaşım nedir?',
    options: [
      { id: 'fam-5a', textEn: 'They move in with us — it\'s our duty', textTr: 'Bizimle kalır — bu bizim görevimiz', value: 1 },
      { id: 'fam-5b', textEn: 'We visit and help daily but they keep their home', textTr: 'Her gün ziyaret edip yardım ederiz ama kendi evinde kalır', value: 2 },
      { id: 'fam-5c', textEn: 'Hire professional help and visit regularly', textTr: 'Profesyonel bakıcı tutar ve düzenli ziyaret ederiz', value: 3 },
      { id: 'fam-5d', textEn: 'A quality care facility with regular visits', textTr: 'Kaliteli bir bakım evi ve düzenli ziyaretler', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
];

// ─── GOALS ───────────────────────────────────────────────────────────
const goalsQuestions: Question[] = [
  {
    id: 'gol-1',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'How ambitious are you about your career?',
    textTr: 'Kariyeriniz konusunda ne kadar hırslısınız?',
    likertLabels: { lowEn: 'Work to live', lowTr: 'Yaşamak için çalışırım', highEn: 'Live to achieve', highTr: 'Başarmak için yaşarım' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-2',
    categoryId: 'goals',
    type: 'scenario',
    textEn: 'Your partner gets an amazing job offer in another country. What do you do?',
    textTr: 'Partneriniz başka bir ülkede harika bir iş teklifi alıyor. Ne yaparsınız?',
    options: [
      { id: 'gol-2a', textEn: 'I\'d move without hesitation — their career matters', textTr: 'Tereddütsüz taşınırdım — kariyeri önemli', value: 1 },
      { id: 'gol-2b', textEn: 'I\'d seriously consider it if the opportunity is great', textTr: 'Fırsat gerçekten iyiyse ciddi olarak düşünürdüm', value: 2 },
      { id: 'gol-2c', textEn: 'Only if my career can also thrive there', textTr: 'Yalnızca benim kariyerim de orada gelişebiliyorsa', value: 3 },
      { id: 'gol-2d', textEn: 'I wouldn\'t uproot my life — we\'d need another solution', textTr: 'Hayatımı kökten değiştirmezdim — başka bir çözüm bulurduk', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-3',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'Where do you see yourself living long-term?',
    textTr: 'Uzun vadede nerede yaşamayı görüyorsunuz kendinizi?',
    likertLabels: { lowEn: 'Near family/hometown', lowTr: 'Aile/memleket yakını', highEn: 'Open to anywhere', highTr: 'Her yere açığım' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-4',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'How important is financial wealth as a life goal?',
    textTr: 'Mali refah bir yaşam hedefi olarak ne kadar önemli?',
    likertLabels: { lowEn: 'Enough to be comfortable', lowTr: 'Rahat etmeye yetecek kadar', highEn: 'Wealth is a top priority', highTr: 'Zenginlik en öncelikli hedefim' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-5',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'How important is continued education and intellectual growth throughout life?',
    textTr: 'Yaşam boyu eğitim ve entelektüel gelişim ne kadar önemli?',
    likertLabels: { lowEn: 'Not a priority', lowTr: 'Öncelikli değil', highEn: 'Lifelong learning is essential', highTr: 'Yaşam boyu öğrenme vazgeçilmez' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── INTIMACY ────────────────────────────────────────────────────────
const intimacyQuestions: Question[] = [
  {
    id: 'int-1',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How important is physical affection (hugging, holding hands, kissing) in daily life?',
    textTr: 'Günlük hayatta fiziksel sevgi gösterileri (sarılma, el tutma, öpüşme) ne kadar önemli?',
    likertLabels: { lowEn: 'Not very important', lowTr: 'Çok önemli değil', highEn: 'Extremely important', highTr: 'Son derece önemli' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-2',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How often do you need quality one-on-one time with your partner?',
    textTr: 'Partnerinizle kaliteli baş başa zaman geçirmeye ne sıklıkla ihtiyaç duyuyorsunuz?',
    likertLabels: { lowEn: 'A few times a month', lowTr: 'Ayda birkaç kez', highEn: 'Every day', highTr: 'Her gün' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-3',
    categoryId: 'intimacy',
    type: 'scenario',
    textEn: 'How do you most naturally express love?',
    textTr: 'Sevginizi en doğal şekilde nasıl ifade edersiniz?',
    options: [
      { id: 'int-3a', textEn: 'Words of affirmation and compliments', textTr: 'Olumlu sözler ve iltifatlar', value: 1 },
      { id: 'int-3b', textEn: 'Acts of service and helping out', textTr: 'Hizmet eylemleri ve yardım etmek', value: 2 },
      { id: 'int-3c', textEn: 'Gifts and thoughtful surprises', textTr: 'Hediyeler ve düşünceli sürprizler', value: 3 },
      { id: 'int-3d', textEn: 'Physical touch and closeness', textTr: 'Fiziksel dokunuş ve yakınlık', value: 4 },
      { id: 'int-3e', textEn: 'Quality time and undivided attention', textTr: 'Nitelikli vakit geçirme ve bölünmemiş ilgi', value: 5 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-4',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How comfortable are you discussing intimate needs and desires openly?',
    textTr: 'Mahrem ihtiyaçlarınızı ve isteklerinizi açıkça konuşmak ne kadar rahat geliyor?',
    likertLabels: { lowEn: 'Very private about this', lowTr: 'Bu konuda çok özel kalırım', highEn: 'Completely open', highTr: 'Tamamen açığım' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-5',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How important is emotional intimacy (deep conversations, sharing fears/dreams) compared to physical intimacy?',
    textTr: 'Fiziksel yakınlığa kıyasla duygusal yakınlık (derin sohbetler, korku/hayalleri paylaşmak) ne kadar önemli?',
    likertLabels: { lowEn: 'Physical is more important', lowTr: 'Fiziksel daha önemli', highEn: 'Emotional is more important', highTr: 'Duygusal daha önemli' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── HOUSEHOLD ───────────────────────────────────────────────────────
const householdQuestions: Question[] = [
  {
    id: 'hsh-1',
    categoryId: 'household',
    type: 'scenario',
    textEn: 'How should household chores be divided?',
    textTr: 'Ev işleri nasıl paylaşılmalı?',
    options: [
      { id: 'hsh-1a', textEn: 'Traditional roles — each person has their domain', textTr: 'Geleneksel roller — her bireyin kendi alanı var', value: 1 },
      { id: 'hsh-1b', textEn: 'Based on who\'s better at what', textTr: 'Kimin neyde daha iyi olduğuna göre', value: 2 },
      { id: 'hsh-1c', textEn: 'Equal 50/50 split of everything', textTr: 'Her şeyin eşit 50/50 paylaşımı', value: 3 },
      { id: 'hsh-1d', textEn: 'Flexible — whoever has more time/energy', textTr: 'Esnek — kimin daha fazla zamanı/enerjisi varsa', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-2',
    categoryId: 'household',
    type: 'likert',
    textEn: 'How clean and organized does your living space need to be?',
    textTr: 'Yaşam alanınızın ne kadar temiz ve düzenli olması gerekiyor?',
    likertLabels: { lowEn: 'Relaxed about mess', lowTr: 'Dağınıklığa aldırmam', highEn: 'Spotlessly clean', highTr: 'Tertemiz olmalı' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-3',
    categoryId: 'household',
    type: 'likert',
    textEn: 'How important is eating meals together as a couple/family?',
    textTr: 'Çift/aile olarak birlikte yemek yemek ne kadar önemli?',
    likertLabels: { lowEn: 'Not important — we eat when convenient', lowTr: 'Önemli değil — uygun olunca yeriz', highEn: 'Essential daily ritual', highTr: 'Vazgeçilmez günlük ritüel' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-4',
    categoryId: 'household',
    type: 'likert',
    textEn: 'How do you feel about hiring help for household tasks (cleaning, cooking)?',
    textTr: 'Ev işleri (temizlik, yemek) için yardım tutmaya nasıl bakıyorsunuz?',
    likertLabels: { lowEn: 'Prefer to do everything ourselves', lowTr: 'Her şeyi kendimiz yapmayı tercih ederiz', highEn: 'Happy to outsource', highTr: 'Dış kaynak kullanmaktan memnuniyet duyarım' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-5',
    categoryId: 'household',
    type: 'scenario',
    textEn: 'Your partner consistently forgets their household responsibilities. How do you handle it?',
    textTr: 'Partneriniz ev sorumluluklarını sürekli unutuyor. Nasıl başa çıkarsınız?',
    options: [
      { id: 'hsh-5a', textEn: 'Just do it myself — not worth the conflict', textTr: 'Kendim hallederim — çatışmaya değmez', value: 1 },
      { id: 'hsh-5b', textEn: 'Gently remind them each time', textTr: 'Her seferinde nazikçe hatırlatırım', value: 2 },
      { id: 'hsh-5c', textEn: 'Have a serious conversation about expectations', textTr: 'Beklentiler hakkında ciddi bir konuşma yaparım', value: 3 },
      { id: 'hsh-5d', textEn: 'Create a shared system (chore chart, app, etc.)', textTr: 'Ortak bir sistem oluştururuz (görev tablosu, uygulama vb.)', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── HEALTH ──────────────────────────────────────────────────────────
const healthQuestions: Question[] = [
  {
    id: 'hlt-1',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How important is regular exercise and physical fitness to you?',
    textTr: 'Düzenli egzersiz ve fiziksel zindelik sizin için ne kadar önemli?',
    likertLabels: { lowEn: 'Not a priority', lowTr: 'Öncelikli değil', highEn: 'Central to my lifestyle', highTr: 'Yaşam tarzımın merkezinde' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hlt-2',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How do you feel about alcohol consumption?',
    textTr: 'Alkol tüketimine nasıl bakıyorsunuz?',
    likertLabels: { lowEn: 'Strictly no alcohol', lowTr: 'Kesinlikle alkol yok', highEn: 'Regular social drinking is fine', highTr: 'Düzenli sosyal içki normaldir' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'hlt-3',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How important is healthy eating and diet to you?',
    textTr: 'Sağlıklı beslenme ve diyet sizin için ne kadar önemli?',
    likertLabels: { lowEn: 'Eat whatever I enjoy', lowTr: 'Sevdiğimi yerim', highEn: 'Very health-conscious diet', highTr: 'Çok sağlık odaklı beslenme' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hlt-4',
    categoryId: 'health',
    type: 'scenario',
    textEn: 'Your partner is going through a mental health struggle (anxiety, depression). What do you expect?',
    textTr: 'Partneriniz ruh sağlığı sorunu yaşıyor (kaygı, depresyon). Ne bekliyorsunuz?',
    options: [
      { id: 'hlt-4a', textEn: 'They should handle it privately — everyone has struggles', textTr: 'Özel olarak halletmeli — herkesin zorlukları var', value: 1 },
      { id: 'hlt-4b', textEn: 'I\'d be supportive but expect them to seek professional help', textTr: 'Destekleyici olurdum ama profesyonel yardım almasını beklerim', value: 2 },
      { id: 'hlt-4c', textEn: 'We tackle it together as a team', textTr: 'Bir takım olarak birlikte üstesinden geliriz', value: 3 },
      { id: 'hlt-4d', textEn: 'I\'d take on extra responsibilities to support their recovery', textTr: 'İyileşmesini desteklemek için ekstra sorumluluk alırım', value: 4 },
    ],
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hlt-5',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How do you feel about smoking (cigarettes, vaping)?',
    textTr: 'Sigara içmeye (sigara, vaping) nasıl bakıyorsunuz?',
    likertLabels: { lowEn: 'Absolutely unacceptable', lowTr: 'Kesinlikle kabul edilemez', highEn: 'Personal choice — no issue', highTr: 'Kişisel tercih — sorun değil' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
];

// ─── SOCIAL ──────────────────────────────────────────────────────────
const socialQuestions: Question[] = [
  {
    id: 'soc-1',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How often do you want to socialize with friends as a couple?',
    textTr: 'Çift olarak arkadaşlarla ne sıklıkla sosyalleşmek istersiniz?',
    likertLabels: { lowEn: 'Rarely — we\'re homebodies', lowTr: 'Nadiren — ev insanlarıyız', highEn: 'Multiple times a week', highTr: 'Haftada birçok kez' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'soc-2',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How do you feel about your partner maintaining close friendships with people of the opposite gender?',
    textTr: 'Partnerinizin karşı cinsle yakın arkadaşlıklar sürdürmesine nasıl bakıyorsunuz?',
    likertLabels: { lowEn: 'Uncomfortable with it', lowTr: 'Rahatsız olurum', highEn: 'Completely fine', highTr: 'Tamamen sorunsuz' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: true,
  },
  {
    id: 'soc-3',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How much alone time do you need in a typical week?',
    textTr: 'Tipik bir haftada ne kadar yalnız zamana ihtiyaç duyuyorsunuz?',
    likertLabels: { lowEn: 'Very little — I want togetherness', lowTr: 'Çok az — birliktelik istiyorum', highEn: 'Significant alone time', highTr: 'Önemli miktarda yalnız zaman' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'soc-4',
    categoryId: 'social',
    type: 'scenario',
    textEn: 'Your partner wants to go on a week-long trip with friends (without you). How do you feel?',
    textTr: 'Partneriniz arkadaşlarıyla bir haftalık bir geziye çıkmak istiyor (sizin olmadığınız). Nasıl hissedersiniz?',
    options: [
      { id: 'soc-4a', textEn: 'I\'d feel hurt — vacations should be together', textTr: 'Incinmiş hissederim — tatiller birlikte olmalı', value: 1 },
      { id: 'soc-4b', textEn: 'A little uneasy but I\'d support it', textTr: 'Biraz rahatsız olurdum ama desteklerdim', value: 2 },
      { id: 'soc-4c', textEn: 'Great — independence is healthy', textTr: 'Harika — bağımsızlık sağlıklıdır', value: 3 },
      { id: 'soc-4d', textEn: 'I\'d encourage it — we both need our own experiences', textTr: 'Teşvik ederim — ikimizin de kendi deneyimlerine ihtiyacı var', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'soc-5',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How much should your partner share about your relationship with their friends/family?',
    textTr: 'Partneriniz ilişkinizi arkadaşlarıyla/ailesiyle ne kadar paylaşmalı?',
    likertLabels: { lowEn: 'Very private — almost nothing', lowTr: 'Çok özel — neredeyse hiçbir şey', highEn: 'Open book — sharing is normal', highTr: 'Açık kitap — paylaşmak normaldir' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── GROWTH ──────────────────────────────────────────────────────────
const growthQuestions: Question[] = [
  {
    id: 'grw-1',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'Do you believe relationships require constant work, or should they flow naturally?',
    textTr: 'İlişkilerin sürekli çaba gerektirdiğine mi yoksa kendiliğinden akması gerektiğine mi inanıyorsunuz?',
    likertLabels: { lowEn: 'Should be natural', lowTr: 'Doğal olmalı', highEn: 'Requires intentional effort', highTr: 'Bilinçli çaba gerektirir' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-2',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'How open are you to couples therapy or counseling, even when things are going well?',
    textTr: 'Her şey yolunda giderken bile çift terapisine veya danışmanlığa ne kadar açıksınız?',
    likertLabels: { lowEn: 'Only in crisis', lowTr: 'Yalnızca kriz anında', highEn: 'Proactive maintenance is great', highTr: 'Önleyici bakım harika bir şey' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-3',
    categoryId: 'growth',
    type: 'scenario',
    textEn: 'Your partner wants to make a major life change (new career, go back to school). How do you respond?',
    textTr: 'Partneriniz büyük bir yaşam değişikliği yapmak istiyor (yeni kariyer, okula geri dönmek). Nasıl tepki verirsiniz?',
    options: [
      { id: 'grw-3a', textEn: 'Stability is important — I\'d discourage risky changes', textTr: 'İstikrar önemli — riskli değişiklikleri caydırırım', value: 1 },
      { id: 'grw-3b', textEn: 'I\'d want a solid plan before supporting it', textTr: 'Desteklemeden önce sağlam bir plan isterim', value: 2 },
      { id: 'grw-3c', textEn: 'I\'d be encouraging and help them figure it out', textTr: 'Teşvik edici olur ve çözmelerine yardımcı olurum', value: 3 },
      { id: 'grw-3d', textEn: 'I\'d be thrilled — growth and reinvention inspire me', textTr: 'Çok heyecanlanırım — büyüme ve yeniden keşfetme beni ilham verir', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-4',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'How important is it for your partner to have their own hobbies and passions?',
    textTr: 'Partnerinizin kendi hobilerinin ve tutkularının olması ne kadar önemli?',
    likertLabels: { lowEn: 'Prefer shared activities', lowTr: 'Ortak aktiviteleri tercih ederim', highEn: 'Individual passions are vital', highTr: 'Bireysel tutkular hayati önem taşır' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-5',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'How do you handle constructive criticism from your partner?',
    textTr: 'Partnerinizden gelen yapıcı eleştiriyle nasıl başa çıkarsınız?',
    likertLabels: { lowEn: 'I take it personally', lowTr: 'Kişisel algılarım', highEn: 'I welcome it as growth', highTr: 'Büyüme fırsatı olarak karşılarım' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
    honestyPairId: 'grw-5-pair',
  },
];

// ─── WORK-LIFE ───────────────────────────────────────────────────────
const worklifeQuestions: Question[] = [
  {
    id: 'wlb-1',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'How many hours per week is it acceptable for a partner to work?',
    textTr: 'Bir partnerinizin haftada kaç saat çalışması kabul edilebilir?',
    likertLabels: { lowEn: 'Strict 40 hours max', lowTr: 'Kesinlikle en fazla 40 saat', highEn: '60+ if needed for success', highTr: 'Başarı için gerekliyse 60+' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-2',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'Should work emails/calls be off-limits during family time?',
    textTr: 'Aile zamanında iş e-postaları/aramaları yasak olmalı mı?',
    likertLabels: { lowEn: 'Work is always on', lowTr: 'İş her zaman açık', highEn: 'Strict boundaries', highTr: 'Katı sınırlar' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-3',
    categoryId: 'worklife',
    type: 'scenario',
    textEn: 'Your partner is offered a promotion that means longer hours and more travel. What\'s your reaction?',
    textTr: 'Partnerinize daha uzun çalışma saatleri ve daha fazla seyahat gerektiren bir terfi teklif ediliyor. Tepkiniz nedir?',
    options: [
      { id: 'wlb-3a', textEn: 'Decline it — family time is more important', textTr: 'Reddetsin — aile zamanı daha önemli', value: 1 },
      { id: 'wlb-3b', textEn: 'Take it only if the extra income is truly needed', textTr: 'Yalnızca ek gelir gerçekten gerekiyorsa kabul etsin', value: 2 },
      { id: 'wlb-3c', textEn: 'Take it — career growth benefits the whole family', textTr: 'Kabul etsin — kariyer gelişimi tüm aileye fayda sağlar', value: 3 },
      { id: 'wlb-3d', textEn: 'Absolutely take it — ambition should be supported', textTr: 'Kesinlikle kabul etsin — hırs desteklenmeli', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-4',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'How important is it that both partners contribute financially to the household?',
    textTr: 'Her iki partnerın da haneye mali katkı sağlaması ne kadar önemli?',
    likertLabels: { lowEn: 'One income is fine', lowTr: 'Tek gelir yeterli', highEn: 'Both must contribute', highTr: 'İkisi de katkıda bulunmalı' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-5',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'How do you feel about working from home versus going to an office?',
    textTr: 'Evden çalışmaya karşı ofise gitmeye nasıl bakıyorsunuz?',
    likertLabels: { lowEn: 'Prefer office — separation matters', lowTr: 'Ofisi tercih ederim — ayrım önemli', highEn: 'Love working from home', highTr: 'Evden çalışmayı seviyorum' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── AESTHETIC ───────────────────────────────────────────────────────
const aestheticQuestions: Question[] = [
  {
    id: 'aes-1',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How important is your partner\'s sense of personal style and appearance?',
    textTr: 'Partnerinizin kişisel tarz ve görünüş anlayışı ne kadar önemli?',
    likertLabels: { lowEn: 'Doesn\'t matter much', lowTr: 'Çok önemli değil', highEn: 'Very important to me', highTr: 'Benim için çok önemli' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-2',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How important is home decor and creating a beautiful living space?',
    textTr: 'Ev dekorasyonu ve güzel bir yaşam alanı oluşturmak ne kadar önemli?',
    likertLabels: { lowEn: 'Functional is enough', lowTr: 'İşlevsel olmak yeterli', highEn: 'Aesthetics matter deeply', highTr: 'Estetik derin bir önem taşır' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-3',
    categoryId: 'aesthetic',
    type: 'scenario',
    textEn: 'Your partner wants to make a major change to their appearance (tattoo, drastic haircut, etc.). How do you feel?',
    textTr: 'Partneriniz görünüşünde büyük bir değişiklik yapmak istiyor (dövme, radikal saç kesimi vb.). Nasıl hissedersiniz?',
    options: [
      { id: 'aes-3a', textEn: 'Their body, their choice — I fully support it', textTr: 'Onun bedeni, onun tercihi — tam destek veririm', value: 1 },
      { id: 'aes-3b', textEn: 'I\'d want to discuss it but ultimately support them', textTr: 'Konuşmak isterdim ama sonuçta desteklerim', value: 2 },
      { id: 'aes-3c', textEn: 'I\'d share my honest opinion and hope they consider it', textTr: 'Dürüst görüşümü paylaşır ve dikkate almalarını umardım', value: 3 },
      { id: 'aes-3d', textEn: 'I\'d be uncomfortable — appearance matters in a partnership', textTr: 'Rahatsız olurdum — görünüş bir ilişkide önemlidir', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-4',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How important are shared taste in music, movies, and entertainment?',
    textTr: 'Müzik, film ve eğlence konusunda ortak zevk ne kadar önemli?',
    likertLabels: { lowEn: 'We can like different things', lowTr: 'Farklı şeyleri sevebiliriz', highEn: 'Shared taste is important', highTr: 'Ortak zevk önemli' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-5',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How do you feel about spending money on luxury or brand-name items?',
    textTr: 'Lüks veya markalı ürünlere para harcamaya nasıl bakıyorsunuz?',
    likertLabels: { lowEn: 'Unnecessary waste', lowTr: 'Gereksiz israf', highEn: 'Quality and brands matter', highTr: 'Kalite ve markalar önemlidir' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── EXPORT ──────────────────────────────────────────────────────────
export const questionsByCategory: Record<CategoryId, Question[]> = {
  values: valuesQuestions,
  communication: communicationQuestions,
  financial: financialQuestions,
  family: familyQuestions,
  goals: goalsQuestions,
  intimacy: intimacyQuestions,
  household: householdQuestions,
  health: healthQuestions,
  social: socialQuestions,
  growth: growthQuestions,
  worklife: worklifeQuestions,
  aesthetic: aestheticQuestions,
};

export const allQuestions: Question[] = Object.values(questionsByCategory).flat();
