import { Question, CategoryId } from '@/lib/types/quiz';

// ─── VALUES ──────────────────────────────────────────────────────────
const valuesQuestions: Question[] = [
  {
    id: 'val-1',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How important is it that your partner shares your religious or spiritual beliefs?',
    textTr: '',
    likertLabels: { lowEn: 'Not important at all', lowTr: '', highEn: 'Absolutely essential', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'val-2',
    categoryId: 'values',
    type: 'scenario',
    textEn: 'Your partner donates a significant portion of income to charity without consulting you. How do you react?',
    textTr: '',
    options: [
      { id: 'val-2a', textEn: 'I\'d be upset — big financial decisions should be joint', textTr: '', value: 1 },
      { id: 'val-2b', textEn: 'I\'d want to discuss it but understand the impulse', textTr: '', value: 2 },
      { id: 'val-2c', textEn: 'I\'d admire their generosity and support it', textTr: '', value: 3 },
      { id: 'val-2d', textEn: 'I\'d be thrilled — generosity is a core value for me', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'val-3',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How closely should your political views align with your partner\'s?',
    textTr: '',
    likertLabels: { lowEn: 'Can be very different', lowTr: '', highEn: 'Must be nearly identical', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'val-4',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How important is honesty, even when the truth is uncomfortable?',
    textTr: '',
    likertLabels: { lowEn: 'White lies are fine', lowTr: '', highEn: 'Total honesty always', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
    honestyPairId: 'val-4-pair',
  },
  {
    id: 'val-5',
    categoryId: 'values',
    type: 'likert',
    textEn: 'How important is it that your partner shares your cultural traditions and heritage?',
    textTr: '',
    likertLabels: { lowEn: 'Not important', lowTr: '', highEn: 'Very important', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
];

// ─── COMMUNICATION ───────────────────────────────────────────────────
const communicationQuestions: Question[] = [
  {
    id: 'com-1',
    categoryId: 'communication',
    type: 'scenario',
    textEn: 'After a heated argument, what do you need most?',
    textTr: '',
    options: [
      { id: 'com-1a', textEn: 'Space to cool down before talking again', textTr: '', value: 1 },
      { id: 'com-1b', textEn: 'A short break, then resolve it the same day', textTr: '', value: 2 },
      { id: 'com-1c', textEn: 'To talk it through immediately until it\'s resolved', textTr: '', value: 3 },
      { id: 'com-1d', textEn: 'Physical reassurance first, then discussion', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-2',
    categoryId: 'communication',
    type: 'likert',
    textEn: 'When your partner is upset, do you try to fix the problem or just listen?',
    textTr: '',
    likertLabels: { lowEn: 'Always fix', lowTr: '', highEn: 'Always listen', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-3',
    categoryId: 'communication',
    type: 'likert',
    textEn: 'How comfortable are you expressing vulnerability and deep emotions to your partner?',
    textTr: '',
    likertLabels: { lowEn: 'Very uncomfortable', lowTr: '', highEn: 'Completely comfortable', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-4',
    categoryId: 'communication',
    type: 'scenario',
    textEn: 'Your partner raises their voice during an argument. What is your response?',
    textTr: '',
    options: [
      { id: 'com-4a', textEn: 'I shut down and go silent', textTr: '', value: 1 },
      { id: 'com-4b', textEn: 'I raise my voice too — it\'s how I express passion', textTr: '', value: 2 },
      { id: 'com-4c', textEn: 'I calmly ask them to lower their voice', textTr: '', value: 3 },
      { id: 'com-4d', textEn: 'I leave the room and come back later', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'com-5',
    categoryId: 'communication',
    type: 'likert',
    textEn: 'How important is it to say "I\'m sorry" after a conflict, even if you don\'t feel entirely wrong?',
    textTr: '',
    likertLabels: { lowEn: 'Only if truly wrong', lowTr: '', highEn: 'Always — repair matters most', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
    honestyPairId: 'com-5-pair',
  },
];

// ─── FINANCIAL ───────────────────────────────────────────────────────
const financialQuestions: Question[] = [
  {
    id: 'fin-1',
    categoryId: 'financial',
    type: 'scenario',
    textEn: 'How should married couples manage their money?',
    textTr: '',
    options: [
      { id: 'fin-1a', textEn: 'Everything in one joint account', textTr: '', value: 1 },
      { id: 'fin-1b', textEn: 'Joint account for shared expenses, separate personal accounts', textTr: '', value: 2 },
      { id: 'fin-1c', textEn: 'Mostly separate with agreed contributions to shared costs', textTr: '', value: 3 },
      { id: 'fin-1d', textEn: 'Completely separate finances', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'fin-2',
    categoryId: 'financial',
    type: 'likert',
    textEn: 'How comfortable are you with taking on debt (mortgage, car loan, credit cards)?',
    textTr: '',
    likertLabels: { lowEn: 'Avoid all debt', lowTr: '', highEn: 'Debt is a normal tool', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fin-3',
    categoryId: 'financial',
    type: 'likert',
    textEn: 'How much should you save versus enjoy life now?',
    textTr: '',
    likertLabels: { lowEn: 'Save aggressively', lowTr: '', highEn: 'Enjoy the present', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fin-4',
    categoryId: 'financial',
    type: 'likert',
    textEn: 'At what spending amount should your partner consult you before purchasing?',
    textTr: '',
    likertLabels: { lowEn: 'Any amount', lowTr: '', highEn: 'Only very large purchases', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fin-5',
    categoryId: 'financial',
    type: 'scenario',
    textEn: 'Your partner\'s family member asks for a large financial loan. What do you do?',
    textTr: '',
    options: [
      { id: 'fin-5a', textEn: 'Family comes first — we should help no matter what', textTr: '', value: 1 },
      { id: 'fin-5b', textEn: 'Help if we can afford it, but set clear boundaries', textTr: '', value: 2 },
      { id: 'fin-5c', textEn: 'Only if they have a repayment plan', textTr: '', value: 3 },
      { id: 'fin-5d', textEn: 'Our household finances come first — politely decline', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── FAMILY ──────────────────────────────────────────────────────────
const familyQuestions: Question[] = [
  {
    id: 'fam-1',
    categoryId: 'family',
    type: 'dealbreaker',
    textEn: 'How important is having children to you?',
    textTr: '',
    likertLabels: { lowEn: 'Do not want children', lowTr: '', highEn: 'Children are essential', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'fam-2',
    categoryId: 'family',
    type: 'scenario',
    textEn: 'How involved should extended family (in-laws) be in your married life?',
    textTr: '',
    options: [
      { id: 'fam-2a', textEn: 'Very involved — family is everything', textTr: '', value: 1 },
      { id: 'fam-2b', textEn: 'Regularly involved but with clear boundaries', textTr: '', value: 2 },
      { id: 'fam-2c', textEn: 'Occasional visits and holidays only', textTr: '', value: 3 },
      { id: 'fam-2d', textEn: 'Minimal involvement — our household is independent', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'fam-3',
    categoryId: 'family',
    type: 'likert',
    textEn: 'How strictly should children be raised?',
    textTr: '',
    likertLabels: { lowEn: 'Very permissive', lowTr: '', highEn: 'Very structured/strict', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fam-4',
    categoryId: 'family',
    type: 'likert',
    textEn: 'Should one parent stay home with young children, or should both parents work?',
    textTr: '',
    likertLabels: { lowEn: 'One parent should stay home', lowTr: '', highEn: 'Both should work', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'fam-5',
    categoryId: 'family',
    type: 'scenario',
    textEn: 'Your aging parent needs daily care. What is the right approach?',
    textTr: '',
    options: [
      { id: 'fam-5a', textEn: 'They move in with us — it\'s our duty', textTr: '', value: 1 },
      { id: 'fam-5b', textEn: 'We visit and help daily but they keep their home', textTr: '', value: 2 },
      { id: 'fam-5c', textEn: 'Hire professional help and visit regularly', textTr: '', value: 3 },
      { id: 'fam-5d', textEn: 'A quality care facility with regular visits', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
];

// ─── GOALS ───────────────────────────────────────────────────────────
const goalsQuestions: Question[] = [
  {
    id: 'gol-1',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'How ambitious are you about your career?',
    textTr: '',
    likertLabels: { lowEn: 'Work to live', lowTr: '', highEn: 'Live to achieve', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-2',
    categoryId: 'goals',
    type: 'scenario',
    textEn: 'Your partner gets an amazing job offer in another country. What do you do?',
    textTr: '',
    options: [
      { id: 'gol-2a', textEn: 'I\'d move without hesitation — their career matters', textTr: '', value: 1 },
      { id: 'gol-2b', textEn: 'I\'d seriously consider it if the opportunity is great', textTr: '', value: 2 },
      { id: 'gol-2c', textEn: 'Only if my career can also thrive there', textTr: '', value: 3 },
      { id: 'gol-2d', textEn: 'I wouldn\'t uproot my life — we\'d need another solution', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-3',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'Where do you see yourself living long-term?',
    textTr: '',
    likertLabels: { lowEn: 'Near family/hometown', lowTr: '', highEn: 'Open to anywhere', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-4',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'How important is financial wealth as a life goal?',
    textTr: '',
    likertLabels: { lowEn: 'Enough to be comfortable', lowTr: '', highEn: 'Wealth is a top priority', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'gol-5',
    categoryId: 'goals',
    type: 'likert',
    textEn: 'How important is continued education and intellectual growth throughout life?',
    textTr: '',
    likertLabels: { lowEn: 'Not a priority', lowTr: '', highEn: 'Lifelong learning is essential', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── INTIMACY ────────────────────────────────────────────────────────
const intimacyQuestions: Question[] = [
  {
    id: 'int-1',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How important is physical affection (hugging, holding hands, kissing) in daily life?',
    textTr: '',
    likertLabels: { lowEn: 'Not very important', lowTr: '', highEn: 'Extremely important', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-2',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How often do you need quality one-on-one time with your partner?',
    textTr: '',
    likertLabels: { lowEn: 'A few times a month', lowTr: '', highEn: 'Every day', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-3',
    categoryId: 'intimacy',
    type: 'scenario',
    textEn: 'How do you most naturally express love?',
    textTr: '',
    options: [
      { id: 'int-3a', textEn: 'Words of affirmation and compliments', textTr: '', value: 1 },
      { id: 'int-3b', textEn: 'Acts of service and helping out', textTr: '', value: 2 },
      { id: 'int-3c', textEn: 'Gifts and thoughtful surprises', textTr: '', value: 3 },
      { id: 'int-3d', textEn: 'Physical touch and closeness', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-4',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How comfortable are you discussing intimate needs and desires openly?',
    textTr: '',
    likertLabels: { lowEn: 'Very private about this', lowTr: '', highEn: 'Completely open', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'int-5',
    categoryId: 'intimacy',
    type: 'likert',
    textEn: 'How important is emotional intimacy (deep conversations, sharing fears/dreams) compared to physical intimacy?',
    textTr: '',
    likertLabels: { lowEn: 'Physical is more important', lowTr: '', highEn: 'Emotional is more important', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── HOUSEHOLD ───────────────────────────────────────────────────────
const householdQuestions: Question[] = [
  {
    id: 'hsh-1',
    categoryId: 'household',
    type: 'scenario',
    textEn: 'How should household chores be divided?',
    textTr: '',
    options: [
      { id: 'hsh-1a', textEn: 'Traditional roles — each person has their domain', textTr: '', value: 1 },
      { id: 'hsh-1b', textEn: 'Based on who\'s better at what', textTr: '', value: 2 },
      { id: 'hsh-1c', textEn: 'Equal 50/50 split of everything', textTr: '', value: 3 },
      { id: 'hsh-1d', textEn: 'Flexible — whoever has more time/energy', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-2',
    categoryId: 'household',
    type: 'likert',
    textEn: 'How clean and organized does your living space need to be?',
    textTr: '',
    likertLabels: { lowEn: 'Relaxed about mess', lowTr: '', highEn: 'Spotlessly clean', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-3',
    categoryId: 'household',
    type: 'likert',
    textEn: 'How important is eating meals together as a couple/family?',
    textTr: '',
    likertLabels: { lowEn: 'Not important — we eat when convenient', lowTr: '', highEn: 'Essential daily ritual', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-4',
    categoryId: 'household',
    type: 'likert',
    textEn: 'How do you feel about hiring help for household tasks (cleaning, cooking)?',
    textTr: '',
    likertLabels: { lowEn: 'Prefer to do everything ourselves', lowTr: '', highEn: 'Happy to outsource', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hsh-5',
    categoryId: 'household',
    type: 'scenario',
    textEn: 'Your partner consistently forgets their household responsibilities. How do you handle it?',
    textTr: '',
    options: [
      { id: 'hsh-5a', textEn: 'Just do it myself — not worth the conflict', textTr: '', value: 1 },
      { id: 'hsh-5b', textEn: 'Gently remind them each time', textTr: '', value: 2 },
      { id: 'hsh-5c', textEn: 'Have a serious conversation about expectations', textTr: '', value: 3 },
      { id: 'hsh-5d', textEn: 'Create a shared system (chore chart, app, etc.)', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── HEALTH ──────────────────────────────────────────────────────────
const healthQuestions: Question[] = [
  {
    id: 'hlt-1',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How important is regular exercise and physical fitness to you?',
    textTr: '',
    likertLabels: { lowEn: 'Not a priority', lowTr: '', highEn: 'Central to my lifestyle', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hlt-2',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How do you feel about alcohol consumption?',
    textTr: '',
    likertLabels: { lowEn: 'Strictly no alcohol', lowTr: '', highEn: 'Regular social drinking is fine', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
  {
    id: 'hlt-3',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How important is healthy eating and diet to you?',
    textTr: '',
    likertLabels: { lowEn: 'Eat whatever I enjoy', lowTr: '', highEn: 'Very health-conscious diet', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hlt-4',
    categoryId: 'health',
    type: 'scenario',
    textEn: 'Your partner is going through a mental health struggle (anxiety, depression). What do you expect?',
    textTr: '',
    options: [
      { id: 'hlt-4a', textEn: 'They should handle it privately — everyone has struggles', textTr: '', value: 1 },
      { id: 'hlt-4b', textEn: 'I\'d be supportive but expect them to seek professional help', textTr: '', value: 2 },
      { id: 'hlt-4c', textEn: 'We tackle it together as a team', textTr: '', value: 3 },
      { id: 'hlt-4d', textEn: 'I\'d take on extra responsibilities to support their recovery', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'hlt-5',
    categoryId: 'health',
    type: 'likert',
    textEn: 'How do you feel about smoking (cigarettes, vaping)?',
    textTr: '',
    likertLabels: { lowEn: 'Absolutely unacceptable', lowTr: '', highEn: 'Personal choice — no issue', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: true,
  },
];

// ─── SOCIAL ──────────────────────────────────────────────────────────
const socialQuestions: Question[] = [
  {
    id: 'soc-1',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How often do you want to socialize with friends as a couple?',
    textTr: '',
    likertLabels: { lowEn: 'Rarely — we\'re homebodies', lowTr: '', highEn: 'Multiple times a week', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'soc-2',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How do you feel about your partner maintaining close friendships with people of the opposite gender?',
    textTr: '',
    likertLabels: { lowEn: 'Uncomfortable with it', lowTr: '', highEn: 'Completely fine', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: true,
  },
  {
    id: 'soc-3',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How much alone time do you need in a typical week?',
    textTr: '',
    likertLabels: { lowEn: 'Very little — I want togetherness', lowTr: '', highEn: 'Significant alone time', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'soc-4',
    categoryId: 'social',
    type: 'scenario',
    textEn: 'Your partner wants to go on a week-long trip with friends (without you). How do you feel?',
    textTr: '',
    options: [
      { id: 'soc-4a', textEn: 'I\'d feel hurt — vacations should be together', textTr: '', value: 1 },
      { id: 'soc-4b', textEn: 'A little uneasy but I\'d support it', textTr: '', value: 2 },
      { id: 'soc-4c', textEn: 'Great — independence is healthy', textTr: '', value: 3 },
      { id: 'soc-4d', textEn: 'I\'d encourage it — we both need our own experiences', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'soc-5',
    categoryId: 'social',
    type: 'likert',
    textEn: 'How much should your partner share about your relationship with their friends/family?',
    textTr: '',
    likertLabels: { lowEn: 'Very private — almost nothing', lowTr: '', highEn: 'Open book — sharing is normal', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── GROWTH ──────────────────────────────────────────────────────────
const growthQuestions: Question[] = [
  {
    id: 'grw-1',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'Do you believe relationships require constant work, or should they flow naturally?',
    textTr: '',
    likertLabels: { lowEn: 'Should be natural', lowTr: '', highEn: 'Requires intentional effort', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-2',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'How open are you to couples therapy or counseling, even when things are going well?',
    textTr: '',
    likertLabels: { lowEn: 'Only in crisis', lowTr: '', highEn: 'Proactive maintenance is great', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-3',
    categoryId: 'growth',
    type: 'scenario',
    textEn: 'Your partner wants to make a major life change (new career, go back to school). How do you respond?',
    textTr: '',
    options: [
      { id: 'grw-3a', textEn: 'Stability is important — I\'d discourage risky changes', textTr: '', value: 1 },
      { id: 'grw-3b', textEn: 'I\'d want a solid plan before supporting it', textTr: '', value: 2 },
      { id: 'grw-3c', textEn: 'I\'d be encouraging and help them figure it out', textTr: '', value: 3 },
      { id: 'grw-3d', textEn: 'I\'d be thrilled — growth and reinvention inspire me', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-4',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'How important is it for your partner to have their own hobbies and passions?',
    textTr: '',
    likertLabels: { lowEn: 'Prefer shared activities', lowTr: '', highEn: 'Individual passions are vital', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'grw-5',
    categoryId: 'growth',
    type: 'likert',
    textEn: 'How do you handle constructive criticism from your partner?',
    textTr: '',
    likertLabels: { lowEn: 'I take it personally', lowTr: '', highEn: 'I welcome it as growth', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
    honestyPairId: 'grw-5-pair',
  },
];

// ─── WORK-LIFE ───────────────────────────────────────────────────────
const worklifeQuestions: Question[] = [
  {
    id: 'wlb-1',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'How many hours per week is it acceptable for a partner to work?',
    textTr: '',
    likertLabels: { lowEn: 'Strict 40 hours max', lowTr: '', highEn: '60+ if needed for success', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-2',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'Should work emails/calls be off-limits during family time?',
    textTr: '',
    likertLabels: { lowEn: 'Work is always on', lowTr: '', highEn: 'Strict boundaries', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-3',
    categoryId: 'worklife',
    type: 'scenario',
    textEn: 'Your partner is offered a promotion that means longer hours and more travel. What\'s your reaction?',
    textTr: '',
    options: [
      { id: 'wlb-3a', textEn: 'Decline it — family time is more important', textTr: '', value: 1 },
      { id: 'wlb-3b', textEn: 'Take it only if the extra income is truly needed', textTr: '', value: 2 },
      { id: 'wlb-3c', textEn: 'Take it — career growth benefits the whole family', textTr: '', value: 3 },
      { id: 'wlb-3d', textEn: 'Absolutely take it — ambition should be supported', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-4',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'How important is it that both partners contribute financially to the household?',
    textTr: '',
    likertLabels: { lowEn: 'One income is fine', lowTr: '', highEn: 'Both must contribute', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'wlb-5',
    categoryId: 'worklife',
    type: 'likert',
    textEn: 'How do you feel about working from home versus going to an office?',
    textTr: '',
    likertLabels: { lowEn: 'Prefer office — separation matters', lowTr: '', highEn: 'Love working from home', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── AESTHETIC ───────────────────────────────────────────────────────
const aestheticQuestions: Question[] = [
  {
    id: 'aes-1',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How important is your partner\'s sense of personal style and appearance?',
    textTr: '',
    likertLabels: { lowEn: 'Doesn\'t matter much', lowTr: '', highEn: 'Very important to me', highTr: '' },
    socialDesirabilityFlag: true,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-2',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How important is home decor and creating a beautiful living space?',
    textTr: '',
    likertLabels: { lowEn: 'Functional is enough', lowTr: '', highEn: 'Aesthetics matter deeply', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-3',
    categoryId: 'aesthetic',
    type: 'scenario',
    textEn: 'Your partner wants to make a major change to their appearance (tattoo, drastic haircut, etc.). How do you feel?',
    textTr: '',
    options: [
      { id: 'aes-3a', textEn: 'Their body, their choice — I fully support it', textTr: '', value: 1 },
      { id: 'aes-3b', textEn: 'I\'d want to discuss it but ultimately support them', textTr: '', value: 2 },
      { id: 'aes-3c', textEn: 'I\'d share my honest opinion and hope they consider it', textTr: '', value: 3 },
      { id: 'aes-3d', textEn: 'I\'d be uncomfortable — appearance matters in a partnership', textTr: '', value: 4 },
    ],
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-4',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How important are shared taste in music, movies, and entertainment?',
    textTr: '',
    likertLabels: { lowEn: 'We can like different things', lowTr: '', highEn: 'Shared taste is important', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
  {
    id: 'aes-5',
    categoryId: 'aesthetic',
    type: 'likert',
    textEn: 'How do you feel about spending money on luxury or brand-name items?',
    textTr: '',
    likertLabels: { lowEn: 'Unnecessary waste', lowTr: '', highEn: 'Quality and brands matter', highTr: '' },
    socialDesirabilityFlag: false,
    dealBreakerFollowUp: false,
  },
];

// ─── EXPORT ──────────────────────────────────────────────────────────
export const questionsByCategory: Record<CategoryId, Question[]> = {
  values: valuesQuestions,
  communication: communicationQuestions,
  financial: financialQuestions,
  family: familyQuestions,
  goals: goalsQuestions,
  intimacy: intimacyQuestions,
  household: householdQuestions,
  health: healthQuestions,
  social: socialQuestions,
  growth: growthQuestions,
  worklife: worklifeQuestions,
  aesthetic: aestheticQuestions,
};

export const allQuestions: Question[] = Object.values(questionsByCategory).flat();
